### ISSUE TITLE
Please add a license file and a readme

### ISSUE THREAD

**Issue by unixorn** [sgpthomas/zsh-up-dir#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add plugins with a readme so that users can tell what features they provide.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by sgpthomas** [comment]
Oh sure. Didn't really anticipate other people using this, but I'm happy to make it a little more presentable

**Comment by sgpthomas** [comment]
added readme and license. thanks for adding this to the list!
